name: Expo CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  expo-build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Check Expo project health
        run: npx expo-doctor

      - name: Try local prebuild (Android & iOS)
        run: CI=1 npx expo prebuild

  eas-build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: expo-build-check
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Run EAS Build (Android)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --non-interactive --profile preview

      - name: Run EAS Build (iOS)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform ios --non-interactive --profile preview
